Grafana Dashboard für kyverno
gepaplexx/gepardec-run-cluster-configuration pull request #133
Opened 2024-01-08 12:01 UTC by tomeindl

Das Dashboard kann am Cluster angesehen werden

2024-01-10 13:13 UTC, hwirnsberger commented
Gerne auch einen Link zum Dashboard hier einfügen @tomeindl 
Ich komme gerade nicht dazu mir das anzuschauen. @fhochleitner kannst du das bitte übernehmen?
Danke

2024-01-10 13:46 UTC, tomeindl commented
Link: https://grafana.play.run.gepardec.com/d/Rg8lWBG7k/kyverno?orgId=1&from=now-2d&to=now

2024-01-11 07:36 UTC, fhochleitner requested changes
Dashboard gefällt mir grundsätzlich sehr gut. 2 Aspekte würde ich allerdings ändern: 

1.) Wie gestern besprochen die Query bei der CPU Usage nicht über die rate anzeigen, sondern über gesamtusage. Siee Slack Verlauf zu dem Thema gestern. 

2.) Das Panel "Latest Status" gibt einen recht schnellen und schönen Überblick über die Rule Evaluation und Success/Failures. Kannst du das vor das Log Panel schieben? Dann hat man zuerst den Überblick ob es Probleme gibt und kann im Fall einen drill-down machen bei Auffälligkeiten und einfach auf die dazupassenden Logs hinunterscrollen. 
![image](https://github.com/gepaplexx/gepardec-run-cluster-configuration/assets/36953096/b4cfa907-fdee-41ee-82d0-a5249a722b2b)

2024-01-11 09:15 UTC, fhochleitner requested changes

2024-01-11 09:15 UTC, fhochleitner commented on observability/dashboards/all/kyverno.yaml
> +      "uid": "Rg8lWBG7k",
die uid bitte noch auf einen sprechenden namen setzen. dann passt es von meiner seite aus. sorry, das hab ich vorher übersehen.

2024-01-11 09:21 UTC, merged