fix/label-values-ns repair broken dashboard variables
gepaplexx/gepardec-run-cluster-configuration pull request #137
Opened 2024-02-29 10:25 UTC by tomeindl

in the Logging Application dashboard

Dashboard can be viewed [here](https://grafana.play.run.gepardec.com/d/logging-application-test/logging-application-test?orgId=1&var-Pod=All&var-Level=.%2B&var-Search=&from=1709201163172&to=1709202063172 ) for review

2024-02-29 10:41 UTC, hwirnsberger requested changes
Kannst du bitte noch beschreiben was sich zu vorher geändert hat?

2024-02-29 10:41 UTC, hwirnsberger commented on observability/dashboards/all/logging_application.yaml
> +      "annotations": {
Das kommt bei einem Export immer wieder rein. Bin mir nicht sicher ob wir es einfach mal drinnen lassen.

2024-02-29 10:41 UTC, hwirnsberger commented on observability/dashboards/all/logging_application.yaml
> -      "id": 17,
id feld sollte egal sein, da das der Grafnaa Operator selbst setzt.

2024-02-29 10:41 UTC, hwirnsberger commented on observability/dashboards/all/logging_application.yaml
> -              "text": "",
mega-backend-prod bitte nicht als default setzen

2024-02-29 10:41 UTC, hwirnsberger commented on observability/dashboards/all/logging_application.yaml
> +            "definition": "label_values({kubernetes_namespace_name=~`$Namespace`}, kubernetes_pod_name)",
~operator entfernen. Ist genaues matching

2024-02-29 10:41 UTC, hwirnsberger commented on observability/dashboards/all/logging_application.yaml
> +              "selected": true,
was hat sich da geändert?

2024-02-29 12:38 UTC, tomeindl commented on observability/dashboards/all/logging_application.yaml
> -            "overrides": []
Hab mit versch. Legenden gespielt und anscheinend hat er das dabei gesetzt, aber wenn man die Legende entfernt bleibt es. Werde es löschen

2024-02-29 12:55 UTC, tomeindl commented
Ich weiß nicht genau was sich geändert habe weil die variablen query war einfach irgendwie kaputt und das ist [[object]] drinnen gestanden. Aber ich schreibe einfach in die merg commit message wie die variablen jetzt zustandekommen

2024-03-01 06:27 UTC, hwirnsberger approved these changes

2024-03-04 08:13 UTC, merged