Feature/gpx 466
gepaplexx/gepardec-run-cluster-configuration pull request #20
Opened 2022-09-01 09:33 UTC by fhochleitner

Keycloak-Operator und Keycloak-Instance zu Inventories unserer Cluster hinzugefügt. 

Encrypted Values auf beiden Clustern ausgetestet. 

Hängt zusammen mit PRs:

2022-09-01 10:42 UTC, gattma requested changes

2022-09-01 10:42 UTC, gattma commented on cluster-setup-checkpoint/gp-cluster-setup-checkpoint/values/values-steppe.yaml
> +            value: "sso.apps.play.gepaplexx.com"
Copy Paste Fehler, sollte vmtl. .steppe. sein

2022-09-01 10:42 UTC, gattma commented on cluster-setup-checkpoint/gp-cluster-setup-checkpoint/values/values-steppe.yaml
> +      targetRevision: "*"
Auf Steppe pinnen wir die Versionen und rollen nur Bugfixes automatisch aus, oder? Vor dem Stern sollte vmtl. was wie 0.1. stehen

2022-09-01 10:42 UTC, gattma commented on initial-cluster-setup/gp-initial-cluster-setup/values/values-steppe.yaml
> +      targetRevision: "*"
auch hier 0.1. vor dem Stern

2022-09-02 05:37 UTC, fhochleitner commented on cluster-setup-checkpoint/gp-cluster-setup-checkpoint/values/values-steppe.yaml
> +            value: "sso.apps.play.gepaplexx.com"
danke, sehr gut gesehen! auch das mit den Versionen. Da wollt ich das Thema wohl schon ein bisschen zu schnell hinter mich bringen :)

2022-09-07 06:20 UTC, merged