Feature/gpx 427
gepaplexx/gepardec-run-cluster-configuration pull request #24
Opened 2022-09-14 12:55 UTC by mario-oberwalder

2022-09-14 14:28 UTC, gattma requested changes

2022-09-14 14:28 UTC, gattma commented on initial-cluster-setup/gp-initial-cluster-setup/values/values-play.yaml
> +          - name: "ldap.bindPassword"
REMINDER: Wenn beim Helm Chart (gp-identity-provider) der Default von enable auf false umgestellt wird, muss er dann hier wieder auf true gesetzt werden (siehe git.enable).

2022-09-14 15:31 UTC, fhochleitner requested changes
in der Steppe dann auch die Minor Version noch hochziehen. 
In den Play Values bitte ldap.enabled explizit auf true setzen. 
in den Defaults auf False

2022-09-14 15:31 UTC, fhochleitner commented on initial-cluster-setup/gp-initial-cluster-setup/Chart.yaml
> +version: 0.1.1
Das Chart hier hat sich nicht geändert. Nur die Values

2022-09-14 15:31 UTC, fhochleitner commented on initial-cluster-setup/gp-initial-cluster-setup/values/values-play.yaml
> +          - name: "ldapUrl"
siehe Anmerkung im PR in gp-helm-chart-development zu meiner Frage bezüglich ldapUrl

2022-09-19 14:02 UTC, gattma approved these changes

2022-09-20 07:25 UTC, merged