Feature/gpx 538
gepaplexx/gepardec-run-cluster-configuration pull request #63
Opened 2023-02-09 10:33 UTC by ShahinMahmody

manuell auf Play & Steppe getestet

2023-02-09 11:18 UTC, sgartner03 approved these changes

2023-02-09 12:44 UTC, Lucostus commented on observability/dashboards/all/pvcs.yml
> +      "refresh": "5s",
Ergibt es wirklich Sinn das alle 5s zu refreshen?

2023-02-09 12:47 UTC, Lucostus requested changes

2023-02-09 12:47 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +            "refresh": 1,
bitte auf "on time range" ändern

2023-02-09 12:47 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +            "refresh": 1,
bitte auf "on time range" ändern

2023-02-09 12:47 UTC, Lucostus commented on observability/dashboards/all/pvcs.yml
> +      "refresh": "5s",
Ergibt es wirklich Sinn das alle 5s zu refreshen?

2023-02-09 13:01 UTC, ShahinMahmody commented on observability/dashboards/all/vault.yml
> +            "refresh": 1,
Refresh jetzt 2

2023-02-09 15:53 UTC, Lucostus requested changes

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/41841989/217862830-381f6ec8-fe19-479d-862f-91ce60dc7654.png">
Panels bitte größer ziehen, unnötige Platz Verschwendung. Node Health Score schiebt vault-2 unter die anderen, sehr komische Ansicht.

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
![image](https://user-images.githubusercontent.com/41841989/217863403-569be26a-aa17-45b4-8567-0c76e815533b.png)
nimmt nicht ganze row ein, größer ziehen.

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
![image](https://user-images.githubusercontent.com/41841989/217863640-7e0a2ceb-3a6c-4ca9-8d00-b37766cc4141.png)
Limits setzen + Farbe? Auch nicht ausgefüllt, aber nicht ganz so schlimm.

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
![image](https://user-images.githubusercontent.com/41841989/217864154-f39e2ab0-6114-4f1c-a6ff-f90065f54876.png)
Log Volume wäre noch hilfreich.

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
![image](https://user-images.githubusercontent.com/41841989/217864606-6c6c6960-e096-4741-afaa-bc7b87e40647.png)
Platz ausfüllen

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
![image](https://user-images.githubusercontent.com/41841989/217864756-80b40913-f5b8-48d1-9cfb-ef3a670ba73d.png)
Platz ausfüllen

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
![image](https://user-images.githubusercontent.com/41841989/217864932-63b7ef60-9575-49f6-b83e-5e37fa13b637.png)
Platz ausfüllen

2023-02-09 15:53 UTC, Lucostus commented on observability/dashboards/all/vault.yml
> +          "type": "row"
![image](https://user-images.githubusercontent.com/41841989/217865088-1f0e9526-1446-41bb-a568-ce7202dec525.png)
Platz ausfüllen oder neu anordnen

2023-02-10 08:40 UTC, Lucostus approved these changes

2023-02-13 13:01 UTC, merged