feature/GPX-538 add keycloak pod and microprofile metrics
gepaplexx/gepardec-run-cluster-configuration pull request #94
Opened 2023-04-05 12:27 UTC by ShahinMahmody

2023-04-07 12:58 UTC, Lucostus requested changes

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +            "orientation": "horizontal",
bitte auf "auto" umstellen. Ist zumindest bei mir Buggy.

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +              "expr": "rate(base_gc_time_total{pod=~\"$pod\", job=\"$serviceID\"}[5m])",
Ist es bewusst nicht gruppiert über verschiedene pods hinweg?

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +              "expr": "rate(base_gc_total{job=~\"$serviceID\", pod=~\"$pod\"}[5m])",
Bewusst nicht gruppiert?

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +                    "color": "red",
Echte Limits wären hier cool

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +                    "color": "red",
Limits und Einheit wäre cool

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +          "title": "Heap Sizes",
Bewusst nicht gruppiert?

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +          "title": "Thread Count",
Bewusst nicht gruppiert?

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +                    "value": 80
limits?

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +            "orientation": "horizontal",
Buggt bei mir herum:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/41841989/230611659-208db6e3-71dc-46c8-a48c-84c1a525bdee.png">

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +            "orientation": "horizontal",
Buggy:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/41841989/230611724-bead7c97-34e1-4f4c-8563-5396a4faf25a.png">

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +            "orientation": "horizontal",
buggy:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/41841989/230611793-ecb6a1b1-db5d-402e-b63d-145e1bf81ed1.png">

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +            "orientation": "horizontal",
Lösung, sum by container, calculation Last.
sum by(container) (base_classloader_loadedClasses_count{pod=~"$pod", job="$serviceID"})
<img width="408" alt="image" src="https://user-images.githubusercontent.com/41841989/230612297-bfe52545-2586-4ecd-a52e-24d4f7f655a6.png">

2023-04-07 12:58 UTC, Lucostus commented on observability/dashboards/all/keycloak.yaml
> +      "title": "Keycloak",
Title, uid, variables, crosshair passt soweit :)

2023-04-12 08:38 UTC, ShahinMahmody commented on observability/dashboards/all/keycloak.yaml
> +                    "color": "red",
Kommen dann mit tatsächlichen Limits am Pod

2023-04-12 08:38 UTC, ShahinMahmody commented on observability/dashboards/all/keycloak.yaml
> +                    "color": "red",
Kommen dann mit tatsächlichen Limits am Pod

2023-04-12 08:38 UTC, ShahinMahmody commented on observability/dashboards/all/keycloak.yaml
> +                    "value": 80
Kommen dann mit tatsächlichen Limits am Pod

2023-04-12 08:47 UTC, merged